#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "geopandas",
# ]
# ///

import geopandas as gpd
import argparse

GEO_URL_ENDPOINT = "https://geo-url.com/"

def main():
    parser = argparse.ArgumentParser(prog='Merge geodata')
    parser.add_argument("input")
    parser.add_argument("-l", "--layer")

    args = parser.parse_args()
    input_file: str = args.input
    layer: str | None = args.layer

    gdf: gpd.GeoDataFrame = gpd.read_file(input_file, layer=layer) # type: ignore
    gdf_layers = list(gpd.list_layers(input_file).name)
    print(f" LAYERS: {gdf_layers}")
    print(f"    CRS: {gdf.crs}")
    print(f"  SHAPE: {gdf.shape}")
    print(f" BOUNDS: {tuple(map(lambda x: float(x), list(gdf.total_bounds)))}")
    bounds_wgs84 = [round(i, 4) for i in list(gdf.to_crs("EPSG:4326").total_bounds)]

    geo_url = GEO_URL_ENDPOINT + f"BBOX(WKT(LINESTRING({bounds_wgs84[0]} {bounds_wgs84[1]}, {bounds_wgs84[2]} {bounds_wgs84[3]})))"
    geo_url = geo_url.replace(" ", "%20")

    print(f" BOUNDS: {tuple(map(lambda x: float(x), bounds_wgs84))}")
    print(f"    URL: {geo_url}")
    print(f"COLUMNS:")
    cols = list(gdf.columns)
    for col in cols:
        datatype = gdf[col].dtype
        print(f"        {col} - {datatype}")




if __name__ == "__main__":
    main()